In [3]:
import numpy as np

In [4]:
np.random.randn(3)

array([-0.39292721, -1.77809169,  0.93633281])

In [15]:
my_list = ['a', 'b', 'c', 'd']

np.random.choice(my_list, 2, replace=True, p=[0.1, 0.7, 0.1 ,0.1]) 
# True 为可放回抽样，False 为不可放回抽样

array(['b', 'b'], dtype='<U1')

In [16]:
target = np.ones((3,1))
target

array([[1.],
       [1.],
       [1.]])

In [17]:
target.T

array([[1., 1., 1.]])

In [18]:
target.reshape(-1)  #  转成一维数组

array([1., 1., 1.])

In [19]:
target = np.arange(9).reshape(3,3)
target

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [20]:
target[:-1, [0,2]]  # 逗号是用来分开维度的，用于选择前面的：-1是指第一个维度（相当于行）从第一个到倒数第二个，
                    # [0，2]是第二个维度（相当于列）第1和第3个

array([[0, 2],
       [3, 5]])

In [21]:
target[:, [0,2]]

array([[0, 2],
       [3, 5],
       [6, 8]])

In [23]:
# cumprod, cumsum 分别表示累乘和累加函数，返回同长度的数组
a = np.array([1,2,3])

a.cumprod()  # 累乘 数据是1, 2, 3，累乘后的结果就是 1, 2, 6（1, 1x2, 1x2x3）


array([1, 2, 6], dtype=int32)

In [24]:
a.cumsum()  # 累加 数据是1, 2, 3，累加后的结果就是 1, 3, 6（1, 1+2, 1+2+3）

array([1, 3, 6], dtype=int32)

In [25]:
np.ones(3)

array([1., 1., 1.])

In [26]:
a = np.arange(4).reshape(-1,2)
a

array([[0, 1],
       [2, 3]])

In [27]:
b = np.arange(-4,0).reshape(-1,2)
b

array([[-4, -3],
       [-2, -1]])

In [28]:
a @ b   #  矩阵的乘法

array([[ -2,  -1],
       [-14,  -9]])

In [29]:
b @ a 

array([[ -6, -13],
       [ -2,  -5]])